"""Seed the `vendors` / `purchase_orders` / `invoices` tables with a small
SYNTHETIC sample so the one-command `docker compose up` dashboard opens with
live data instead of "0 invoices ingested".

Usage (run inside the compose network, e.g. the init-db one-shot):
    python scripts/seed_sample_invoices.py

Needs: DATABASE_URL pointing at the Postgres from docker-compose.yml, and
the sentence-transformers dependency (all-MiniLM-L6-v2 weights) so invoice
texts get real embeddings via core/document_ai.py — the same encoder
scripts/seed_policies.py uses for policies.

Honesty notes (do not remove):
- Every row is SYNTHETIC, generated by scripts/synthesize.py with a fixed
  seed. Invoice numbers are prefixed "SAMPLE-" so sample rows are
  distinguishable from real data at the data level, and the dashboard
  labels them as sample data.
- This seed does NOT touch the 250K-invoice accuracy claim or the 93.3%
  eval: those were measured on their own corpora. It only populates the
  reviewer's local database.
- Idempotent: if the invoices table already has rows, the script exits
  without inserting anything.
- Opt-out: set SEED_SAMPLE_INVOICES=0 to skip seeding entirely (e.g. to
  keep byte-identical conditions for eval reruns against this database).

Side effect worth knowing: with >=100 invoices present, the API's startup
XGBoost training (AnomalyScoringEngine.train_model) now trains on this
sample instead of logging "Not enough data to train model" — which also
makes first audits faster (no 10s fallback training on first /audit call).
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pandas as pd
from sqlalchemy import text
from sqlalchemy.orm import Session

from database.db import Base, Invoice, PurchaseOrder, Vendor, engine

SAMPLE_INVOICES = int(os.getenv("SEED_SAMPLE_INVOICES", "500"))
SAMPLE_POS = 40
SYNTH_SEED = 123


def _get_encoder():
    try:
        from core.document_ai import DocumentAIProcessor
    except Exception as e:  # noqa: BLE001 - sentence_transformers missing
        raise SystemExit(
            "seed_sample_invoices.py needs the embedding dependency: "
            "pip install sentence-transformers (and network access to download "
            f"the all-MiniLM-L6-v2 weights). Underlying error: {e}"
        ) from e
    return DocumentAIProcessor()


def main() -> None:
    if SAMPLE_INVOICES <= 0:
        print("SEED_SAMPLE_INVOICES=0 — skipping sample invoice seed.")
        return

    Base.metadata.create_all(engine)
    with Session(engine) as session:
        existing = session.query(Invoice).count()
        if existing:
            print(f"invoices table already has {existing} rows — skipping seed.")
            return

        from scripts.synthesize import (
            make_invoices,
            make_purchase_orders,
            make_vendors,
        )

        vendors = make_vendors(seed=SYNTH_SEED)
        pos = make_purchase_orders(vendors, n=SAMPLE_POS, seed=SYNTH_SEED)
        inv = make_invoices(vendors, pos, total=SAMPLE_INVOICES, seed=SYNTH_SEED)
        print(f"Generated {len(vendors)} vendors, {len(pos)} POs, "
              f"{len(inv)} synthetic invoices.")

        for v in vendors.itertuples():
            if session.query(Vendor).filter_by(tax_id=v.tax_id).first():
                continue
            session.add(Vendor(
                vendor_id=int(v.vendor_id),
                name=v.name, tax_id=v.tax_id, bank_account=v.bank_account,
                address=v.address, risk_rating=float(v.risk_rating),
            ))
        session.flush()

        for p in pos.itertuples():
            if session.query(PurchaseOrder).filter_by(po_number=p.po_number).first():
                continue
            session.add(PurchaseOrder(
                po_id=int(p.po_id), po_number=p.po_number,
                vendor_id=int(p.vendor_id),
                department_id=p.department_id,
                amount_limit=float(p.amount_limit), status=p.status,
                issue_date=pd.to_datetime(p.issue_date).date(),
            ))
        session.flush()

        # Real MiniLM embeddings so invoice-similarity retrieval works on
        # the sample data (same encoder as seed_policies.py).
        encoder = _get_encoder()
        texts = inv["raw_text"].fillna("").tolist()
        print(f"Embedding {len(texts)} invoice texts "
              f"(all-MiniLM-L6-v2, 384-dim, normalized)...")
        embeddings = [encoder.generate_embedding(t) for t in texts]

        for row, emb in zip(inv.itertuples(), embeddings):
            session.add(Invoice(
                invoice_number=f"SAMPLE-{row.invoice_number}",
                vendor_id=int(row.vendor_id), po_id=int(row.po_id),
                invoice_date=pd.to_datetime(row.invoice_date).date(),
                subtotal=float(row.subtotal), tax_amount=float(row.tax_amount),
                total_amount=float(row.total_amount), raw_text=row.raw_text,
                embedding=emb, status=row.status,
            ))
        session.commit()
        # Keep the auto-increment sequences ahead of the explicitly-set IDs.
        for seq, table, col in [
            ("vendors_vendor_id_seq", "vendors", "vendor_id"),
            ("purchase_orders_po_id_seq", "purchase_orders", "po_id"),
            ("invoices_invoice_id_seq", "invoices", "invoice_id"),
        ]:
            session.execute(
                text(f"SELECT setval('{seq}', (SELECT max({col}) FROM {table}))")
            )
        session.commit()
        print(f"Seeded {SAMPLE_INVOICES} SAMPLE- synthetic invoices "
              f"({(inv['status'] == 'FLAGGED').sum()} flagged).")


if __name__ == "__main__":
    main()
